# Site settings
author: Nathan Peirson
title: Seeking the Signal
header-img: img/home-bg.png
email: peirson.n@gmail.com
copyright_name: Nathan Peirson
description: > # this means to ignore newlines until "baseurl:"
  an eigenblog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  npeirson

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
